name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to gh-pages
      run: |
        git config user.email "jazzlaug@mandaljazz.no"
        git config user.name "Sjau Jazzlaug"
        yarn install
        yarn deploy
