name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "jazzlaug@mandaljazz.no"
        git config --local user.name "Sjau Jazzlaug"
        git remote set-url --push origin https://hanshenrik:$GITHUB_TOKEN@github.com/mandaljazz/mandaljazz.no
        yarn install
        yarn deploy
